version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - "8000:8000"
    command: 
      - start
      - -A
      - --auth
      - --no-banner
      - --log=trace
      - --user=root
      - --pass=root
      - memory