-- table
DEFINE TABLE records SCHEMALESS PERMISSIONS NONE;

-- fields

-- indexes

-- events
DEFINE EVENT records_log ON TABLE records WHEN $event = "CREATE" OR $event = "UPDATE" OR $event = "DELETE" THEN {
  IF $event = 'DELETE' {
    CREATE logs SET index = $before.id, event = $event, time = time::now();
  } ELSE {
    CREATE logs SET index = $value.id, event = $event, time = time::now();
  }
};
