create questions content {
  question: [ {
    locale: 'es',
    content: '¿Cómo te llamas?'
  },{
    locale: 'en',
    content: 'what is your name?'
  },{
    locale: 'fr',
    content: 'quel est votre nom?'
  } ]
}

UPDATE <id> CONTENT {
  question: [ {
    locale: 'en',
    content: 'What is your name?'
  },{
    locale: 'fr',
    content: 'Quel est votre nom?'
  },{
    locale: 'de',
    content: 'Wie heißen Sie?'
  },{
    locale: 'es',
    content: '¿Cómo te llamas?'
  } ]
}
